apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acm.yaml
patches:
  - target:
      apiVersion: hive.openshift.io/v1
      kind: HiveConfig
      name: hive
    patch: |-
      apiVersion: hive.openshift.io/v1
      kind: HiveConfig
      metadata:
        name: hive
      spec:
        globalPullSecret:
          name: ocp-pull-secret
          namespace: openshift-cluster-management
