# This resources enables you to customize the ArgoCD server configuration
# that the oprerator creates to install ArgoCD into the cluster.
# See this article for the complete specification:
# https://argocd-operator.readthedocs.io/en/latest/reference/argocd/
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: openshift-gitops
data: {}
