apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operators.yaml
  - resources.yaml
  - secrets.yaml
  - managedclusters.yaml
  - importedclusters.yaml
  - submariner.yaml
