apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operators.yaml
  - resources.yaml
  - secrets.yaml
  - managedcluster_aws.yaml
  - managedcluster_gcp.yaml
  - submariner_aws.yaml
  - submariner_gcp.yaml
  - submariner_broker.yaml
